DungeonsAndDragonsMonsterFinder/Models/ErrorViewModel.cs
namespace DungeonsAndDragonsMonsterFinder.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DungeonsAndDragonsMonsterFinder/Models/Monsters.cs
namespace DungeonsAndDragonsMonsterFinder.Models
{
    public class Monsters
    {
        public Monsters()
        {

        }
        public int MonsterId { get; set; }
        public string Name { get; set; }
        public string Meta { get; set; }
        public string ArmorClass { get; set; }
        public string HitPoints { get; set; }
        public string Speed { get; set; }
        public int STR { get; set; }
        public string STR_mod { get; set; }
        public int DEX { get; set; }
        public string DEX_mod { get; set; }
        public int CON { get; set; }
        public string CON_mod { get; set; }
        public int INT { get; set; }
        public string INT_mod { get; set; }
        public int WIS { get; set; }
        public string WIS_mod { get; set; }
        public int CHA { get; set; }
        public string CHA_mod { get; set; }
        public string SavingThrows { get; set; }
        public string Skills { get; set; }
        public string Senses { get; set; }
        public string Languages { get; set; }
        public string Challenge { get; set; }
        public string Traits { get; set; }
        public string Actions { get; set; }
        public string LegendaryActions { get; set; }
        public string img_url { get; set; }
        public string DamageImmunities { get; set; }
        public string ConditionImmunities { get; set; }
        public string DamageResistances { get; set; }
        public string DamageVulnerabilities { get; set; }
        public string Reactions { get; set; }
    }

}

DungeonsAndDragonsMonsterFinder/Controllers/HomeController.cs
using DungeonsAndDragonsMonsterFinder.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DungeonsAndDragonsMonsterFinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DungeonsAndDragonsMonsterFinder/Controllers/MonstersController.cs
using DungeonsAndDragonsMonsterFinder.Models;
using DungeonsAndDragonsMonsterFinder.MonsterRepo;
using Microsoft.AspNetCore.Mvc;

namespace DungeonsAndDragonsMonsterFinder.Controllers
{
    public class MonstersController : Controller
    {
        private readonly IMonsterRepository repo;


        public MonstersController(IMonsterRepository repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var monster = repo.GetAllMonsters().ToList();
            return View(monster);
        }

        public IActionResult Search(string searchStringName)
        {
            var searchResults = repo.SearchMonstersName(searchStringName);
            return View(searchResults);
        }


        public IActionResult SearchMonstersMetaSize(string size)
        {
            var searchResults = repo.SearchMonstersMetaSize(size);
            return View(searchResults);
        }

        public IActionResult SearchMonstersLanguages(string language)
        {
            var searchResults = repo.SearchMonstersLanguages(language);
            return View(searchResults);
        }

        public IActionResult SearchMonstersTraits(string trait)
        {
            var searchResults = repo.SearchMonstersTraits(trait);
            return View(searchResults);
        }

        public IActionResult IndividualView(int monsterId)
        {
            var monster = repo.GetMonster(monsterId);
            return View(monster);
        }

        public IActionResult SearchMonstersActions(string action)
        {
            var searchResults = repo.SearchMonstersActions(action);
            return View(searchResults);
        }

        public IActionResult SearchMonstersMeta(string meta)
        {
            var searchResults = repo.SearchMonstersMeta(meta);
            return View(searchResults);
        }
        public IActionResult SearchMonstersChallenge(string challenge)
        {
            var searchResults = repo.SearchMonstersChallenge(challenge);
            return View(searchResults);
        }
        public IActionResult RandomMonster()
        {
            var monsters = repo.GetAllMonsters().ToList();
            var random = new Random();
            var randomMonster = monsters[random.Next(monsters.Count)];

            return View(randomMonster);
        }
        public IActionResult GetMonster(int id)
        {
            var monster = repo.GetMonster(id);
            return View(monster);
        }
        public IActionResult UpdateMonster(int id)
        {
            Monsters monster = repo.GetMonster(id);
            if (monster == null)
            {
                return View("ProductNotFound");
            }
            return View(monster);
        }
        public IActionResult UpdateMonsterToDatabase(Monsters monster)
        {
            repo.UpdateMonster(monster);

            return RedirectToAction("GetMonster", new { id = monster.MonsterId });
        }


        public IActionResult InsertMonster()
        {

            return View();
        }
        public IActionResult InsertMonsterToDatabase(Monsters monster)
        {
            repo.InsertMonster(monster);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteMonster(Monsters monster)
        {
            repo.DeleteMonster(monster);
            return RedirectToAction("Index");
        }
    }
}

DungeonsAndDragonsMonsterFinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<html lang="en">
<style>
    body {
        background-color: black;
      
        
</style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Monster Finder</title>
</head>
<body>
    
    <h1 class="display-4"> D&D Monster Finder</h1>
    <button class="btn btn-start-searching" onclick="window.location.href='/Monsters/Index'">Start Searching!</button>
    <button class="btn btn-start-searching" onclick="window.location.href='/Monsters/InsertMonster'">Create A Monster!</button>
    <div>
    <p>
    </p>
    <a asp-controller="Monsters" asp-action="RandomMonster" class="btn btn-random">Randomize a Monster!</a>
    </div>
</body>
</html>

@* 
<head>
    <meta charset= "utf-8"

</head>
<div class="text-center">
    <h1 class="display-4">Monster Finder</h1>
    <p</p>
</div> *@

DungeonsAndDragonsMonsterFinder/Views/Monsters/GetMonster.cshtml
@model Monsters

<style>
    body {
        background-color: black;
        background-image: none;
    }


    <style >
    body {
        background-color: rgb(32,32,32);
        background-image: none;
    }
</style>

<div class="search-bar">


        @using (Html.BeginForm("SearchMonstersTraits", "Monsters", FormMethod.Get))
        {
        <p>
            Search Traits: @Html.TextBox("trait")
            <input type="submit" value="Search" />
        </p>
        }


        @using (Html.BeginForm("SearchMonstersMetaSize", "Monsters", FormMethod.Post))
        {
        <p>
            Size:
            <select name="size">
                <option value="--">Sizes</option>
                    @foreach (var size in new List<string>
            {
            "Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"

            })
                    {
                    <option value="@size">@size</option>
                    }
            </select>
            <input type="submit" value="Sort" />
        </p>
        }
        @using (Html.BeginForm("SearchMonstersChallenge", "Monsters", FormMethod.Post))
        {
        <p>
            Challenge Level:
            <select name="challenge">
                <option value="--">Challenge</option>
                    @foreach (var challenge in new List<string>
            {
            "0", "1/8", "1/4", "1/2", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"

            })
                    {
                    <option value="@challenge">@challenge</option>
                    }
            </select>
            <input type="submit" value="Sort" />
        </p>
        }
</div>
<div class="search-bar">

        @using (Html.BeginForm("SearchMonstersLanguages", "Monsters", FormMethod.Post))
        {
        <p>
            Languages:
            <select name="language">
                <option value="--">Languages</option>
                    @foreach (var language in new List<string>
            {
            "Abyssal", "Aquan", "Auran", "Blink Dog", "Celestial", "Common", "creator", "Deep Speech",
            "Draconic", "Elvish", "Giant", "Ignan", "Infernal", "Sphinx", "Telepathy", "Thieves", "Undercommon"

            })
                    {
                    <option value="@language">@language</option>
                    }
            </select>
            <input type="submit" value="Sort" />
        </p>
        }
        @using (Html.BeginForm("SearchMonstersActions", "Monsters", FormMethod.Post))
        {
        <p>
            Action:
            <select name="action">
                <option value="--">Actions</option>
                    @foreach (var action in new List<string>
            {
            "Beak", "Bite", "Claw", "Club", "Corrupting Touch", "Crush", "Dagger", "Enlarge", "Fist", "Gore",
            "Great Axe", "Great Club", "Life Drain", "Longsword", "Mace", "MorningStar", "Multi Attack",
            "Paralyzing Touch", "Psuedopod", "Quaterstaff", "Rake", "Ram", "Scimitar", "Shortsword", "Slam",
            "Spear", "Spiked Bone Club", "Sting", "Strength Drain", "Tail", "Tentacles", "Touch", "Tusk",
            "War Pick", "Warhammer", "Withering Touch"
            })
                    {
                    <option value="@action">@action</option>
                    }
            </select>
            <input type="submit" value="Sort" />
        </p>
        }
        @using (Html.BeginForm("SearchMonstersMeta", "Monsters", FormMethod.Post))
        {
        <p>
            Alignment:
            <select name="meta">
                <option value="--">Alignment</option>
                    @foreach (var meta in new List<string>
            {
            "Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil", "Unaligned"
            })
                    {
                    <option value="@meta">@meta</option>
                    }
            </select>
            <input type="submit" value="Sort" />
        </p>
        }
</div>


<div id="monsterBox" class="flex-container">
    <div style="display: block">
        <a href="/Monsters/UpdateMonster/@Model.MonsterId">Update this Monster</a>
    </div>
    <div id="monster-image">
        <img src="@Model.img_url" />
    </div>


    <div id="monster-info">
        <h2>@Model.Name</h2>
        <p>@Model.Meta</p>

        <div id="flex-container">
            <div id="column">
                <div id="attributes">
                    <h3>Attributes</h3>
                    <p>Armor Class: @Model.ArmorClass</p>
                    <p>Hit Points: @Model.HitPoints</p>
                    <p>Speed: @Model.Speed</p>
                </div>
            </div>

            <div id="column">
                <div id="abilities">
                    <h3>Abilities</h3>
                    <div id="ability-column">
                        <p>STR: @Model.STR (@Model.STR_mod)</p>
                        <p>DEX: @Model.DEX (@Model.DEX_mod)</p>
                    </div>
                    <div id="ability-column">
                        <p>CON: @Model.CON (@Model.CON_mod)</p>
                        <p>INT: @Model.INT (@Model.INT_mod)</p>
                    </div>
                    <div id="ability-column">
                        <p>WIS: @Model.WIS (@Model.WIS_mod)</p>
                        <p>CHA: @Model.CHA (@Model.CHA_mod)</p>
                    </div>
                </div>
            </div>

            <div id="column">
                <div class="other-details">
                    <h3>Other Details</h3>
                    <p><strong>Saving Throws:</strong> @Model.SavingThrows</p>
                    <p><strong>Skills:</strong> @Model.Skills</p>
                    <p><strong>Senses:</strong> @Model.Senses</p>
                    <p><strong>Languages:</strong> @Model.Languages</p>
                    <p><strong>Challenge:</strong> @Model.Challenge</p>
                </div>
            </div>
        </div>
        <div id="traits">
            <h3>Traits</h3>
            <p>@Model.Traits</p>
        </div>
    </div>

    <div id="column">
            @if (!string.IsNullOrEmpty(Model.Actions))
            {
            <div class="actions">
                <h3>Actions</h3>
                <p>@Model.Actions</p>
            </div>
            }

            @if (!string.IsNullOrEmpty(Model.LegendaryActions))
            {
            <div class="legendary-actions">
                <h3>Legendary Actions</h3>
                <p>@Model.LegendaryActions</p>
            </div>
            }

            @if (!string.IsNullOrEmpty(Model.DamageImmunities))
            {
            <div class="damage-immunities">
                <h3>Damage Immunities</h3>
                <p>@Model.DamageImmunities</p>
            </div>
            }

            @if (!string.IsNullOrEmpty(Model.ConditionImmunities))
            {
            <div class="condition-immunities">
                <h3>Condition Immunities</h3>
                <p>@Model.ConditionImmunities</p>
            </div>
            }

            @if (!string.IsNullOrEmpty(Model.DamageResistances))
            {
            <div class="damage-resistances">
                <h3>Damage Resistances</h3>
                <p>@Model.DamageResistances</p>
            </div>
            }

            @if (!string.IsNullOrEmpty(Model.DamageVulnerabilities))
            {
            <div class="damage-vulnerabilities">
                <h3>Damage Vulnerabilities</h3>
                <p>@Model.DamageVulnerabilities</p>
            </div>

            }
      
            <div style="display: block">

                    @using (Html.BeginForm("DeleteMonster", "Monsters", "Post"))
                    {
                    <input type="hidden" asp-for="MonsterId" value="@Model.MonsterId" />
                    <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this monster" />
                    }
            </div>
        </div>
    </div>
</div>

DungeonsAndDragonsMonsterFinder/Views/Monsters/Index.cshtml
@model IEnumerable<Monsters>

<style>
    body {
        background-color: rgb(32,32,32);
        background-image: none;
    }
</style>

<div class="search-bar">
    

    @using (Html.BeginForm("SearchMonstersTraits", "Monsters", FormMethod.Get))
    {
        <p>
            Search Traits: @Html.TextBox("trait")
            <input type="submit" value="Search" />
        </p>
    }


    @using (Html.BeginForm("SearchMonstersMetaSize", "Monsters", FormMethod.Post))
    {
        <p>
            Size:
            <select name="size">
                <option value="--">Sizes</option>
                @foreach (var size in new List<string>
            {
            "Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"

            })
                {
                    <option value="@size">@size</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
    @using (Html.BeginForm("SearchMonstersChallenge", "Monsters", FormMethod.Post))
    {
        <p>
            Challenge Level:
            <select name="challenge">
                <option value="--">Challenge</option>
                @foreach (var challenge in new List<string>
            {
            "0", "1/8", "1/4", "1/2", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"

            })
                {
                    <option value="@challenge">@challenge</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
</div>
<div class="search-bar">

    @using (Html.BeginForm("SearchMonstersLanguages", "Monsters", FormMethod.Post))
    {
        <p>
            Languages:
            <select name="language">
                <option value="--">Languages</option>
                @foreach (var language in new List<string>
            {
            "Abyssal", "Aquan", "Auran", "Blink Dog", "Celestial", "Common", "creator", "Deep Speech",
            "Draconic", "Elvish", "Giant", "Ignan", "Infernal", "Sphinx", "Telepathy", "Thieves", "Undercommon"
            
            })
                {
                    <option value="@language">@language</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
    @using (Html.BeginForm("SearchMonstersActions", "Monsters", FormMethod.Post))
    {
        <p>
            Action:
            <select name="action">
                <option value="--">Actions</option>
                @foreach (var action in new List<string>
            {
            "Beak", "Bite", "Claw", "Club", "Corrupting Touch", "Crush", "Dagger", "Enlarge", "Fist", "Gore",
            "Greataxe", "Greatclub", "Life Drain", "Longsword", "Mace", "MorningStar", "Multi Attack",
            "Paralyzing Touch", "Psuedopod", "Quaterstaff", "Rake", "Ram", "Scimitar", "Shortsword", "Slam",
            "Spear", "Spiked Bone Club", "Sting", "Strength Drain", "Tail", "Tentacles", "Touch", "Tusk",
            "War Pick", "Warhammer", "Withering Touch"
            })
                {
                    <option value="@action">@action</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
    @using (Html.BeginForm("SearchMonstersMeta", "Monsters", FormMethod.Post))
    {
        <p>
            Alignment:
            <select name="meta">
                <option value="--">Alignment</option>
                @foreach (var meta in new List<string>
            {
            "Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil", "Unaligned"
            })
                {
                    <option value="@meta">@meta</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
</div>
<div style="display: block">
    <button class="btn btn-start-searching" onclick="window.location.href='/Monsters/InsertMonster'">Create A Monster!</button>
</div>

<h1 style ="color:darkgoldenrod">Monster List</h1>


<table class="custom-table">
    <thead>
        <tr>
            <th>MonsterID</th>
            <th>Image</th>
            <th>Name</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var monster in Model)
        {
            <tr>
                <td><a href="/Monsters/GetMonster/@monster.MonsterId">@monster.MonsterId</a></td>
                <td><img src="@monster.img_url" alt="@monster.Name" class="monster-image" /></td>
                <td style="color: rgb(242, 141, 107);">@monster.Name</td>
                <td><a href="/Monsters/IndividualView?MonsterId=@monster.MonsterId" class="details-link" style="color: blue;">View Details</a></td>
            </tr>
        }
    </tbody>
</table>

DungeonsAndDragonsMonsterFinder/Views/Monsters/IndividualView.cshtml
@model Monsters

<style>
    body {
        background-color: black;
        
        background-image: none;
    }
</style>
<div class="search-bar">


    @using (Html.BeginForm("SearchMonstersTraits", "Monsters", FormMethod.Get))
    {
        <p>
            Find by Trait: @Html.TextBox("trait")
            <input type="submit" value="Search" />
        </p>
    }

    @using (Html.BeginForm("SearchMonstersMetaSize", "Monsters", FormMethod.Post))
    {
        <p>
            Size:
            <select name="size">
                <option value="Tiny">Tiny</option>
                <option value="Small">Small</option>
                <option value="Medium">Medium</option>
                <option value="Large">Large</option>
                <option value="Huge">Huge</option>
                <option value="Gargantuan">Gargantuan</option>
            </select>
            <input type="submit" value="Sort" />
        </p>
    }

    @using (Html.BeginForm("SearchMonstersLanguages", "Monsters", FormMethod.Post))
    {
        <p>
            Language:
            <select name="language">
                <option value="--">No Language</option>
                <option value="Abyssal">Abyssal</option>
                <option value="Aquan">Aquan</option>
                <option value="Auran">Auran</option>
                <option value="Blink Dog">Blink Dog</option>
                <option value="Celestial">Celestial</option>
                <option value="Common">Common</option>
                <option value="creator">Creator</option>
                <option value="Deep Speech">Deep Speech</option>
                <option value="Draconic">Draconic</option>
                <option value="Elvish">Elvish</option>
                <option value="Giant">Giant</option>
                <option value="Ignan">Ignan</option>
                <option value="Infernal">Infernal</option>
                <option value="Sphinx">Sphinx</option>
                <option value="Telepathy">Telepathy</option>
                <option value="Thieves">Thieves</option>
                <option value="Undercommon">Undercommon</option>
            </select>
            <input type="submit" value="Sort" />
        </p>
    }

    @using (Html.BeginForm("SearchMonstersActions", "Monsters", FormMethod.Post))
    {
        <p>
            Action:
            <select name="action">
                <option value="--">No Action</option>
                @foreach (var action in new List<string>
            {
            "Beak", "Bite", "Claw", "Club", "Corrupting Touch", "Crush", "Dagger", "Enlarge", "Fist", "Gore",
            "Greataxe", "Greatclub", "Life Drain", "Longsword", "Mace", "MorningStar", "Multi Attack",
            "Paralyzing Touch", "Psuedopod", "Quaterstaff", "Rake", "Ram", "Scimitar", "Shortsword", "Slam",
            "Spear", "Spiked Bone Club", "Sting", "Strength Drain", "Tail", "Tentacles", "Touch", "Tusk",
            "War Pick", "Warhammer", "Withering Touch"
            })
                {
                    <option value="@action">@action</option>
                }
            </select>
            <input type="submit" value="Sort" />
        </p>
    }
</div>


<div id="monsterBox" class="flex-container">
    <div id="monster-image">
        <img src="@Model.img_url" />
    </div>

    <div id="monster-info">
        <h2>@Model.Name</h2>
        <p>@Model.Meta</p>

        <div id="flex-container">
            <div id="column">
                <div id="attributes">
                    <h3>Attributes</h3>
                    <p>Armor Class: @Model.ArmorClass</p>
                    <p>Hit Points: @Model.HitPoints</p>
                    <p>Speed: @Model.Speed</p>
                </div>
            </div>

            <div id="column">
                <div id="abilities">
                    <h3>Abilities</h3>
                    <div class="ability-column">
                        <p>STR: @Model.STR (@Model.STR_mod)</p>
                        <p>DEX: @Model.DEX (@Model.DEX_mod)</p>
                    </div>
                    <div class="ability-column">
                        <p>CON: @Model.CON (@Model.CON_mod)</p>
                        <p>INT: @Model.INT (@Model.INT_mod)</p>
                    </div>
                    <div class="ability-column">
                        <p>WIS: @Model.WIS (@Model.WIS_mod)</p>
                        <p>CHA: @Model.CHA (@Model.CHA_mod)</p>
                    </div>
                </div>
            </div>

            <div id="column">
                <div class="other-details">
                    <h3>Other Details</h3>
                    <p><strong>Saving Throws:</strong> @Model.SavingThrows</p>
                    <p><strong>Skills:</strong> @Model.Skills</p>
                    <p><strong>Senses:</strong> @Model.Senses</p>
                    <p><strong>Languages:</strong> @Model.Languages</p>
                    <p><strong>Challenge:</strong> @Model.Challenge</p>
                </div>
            </div>
        </div>
                <div id="traits">
                    <h3>Traits</h3>
                    <p>@Model.Traits</p>
                </div>
            </div>

            <div id="column">
                @if (!string.IsNullOrEmpty(Model.Actions))
                {
                    <div class="actions">
                        <h3>Actions</h3>
                        <p>@Model.Actions</p>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.LegendaryActions))
                {
                    <div class="legendary-actions">
                        <h3>Legendary Actions</h3>
                        <p>@Model.LegendaryActions</p>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.DamageImmunities))
                {
                    <div class="damage-immunities">
                        <h3>Damage Immunities</h3>
                        <p>@Model.DamageImmunities</p>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.ConditionImmunities))
                {
                    <div class="condition-immunities">
                        <h3>Condition Immunities</h3>
                        <p>@Model.ConditionImmunities</p>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.DamageResistances))
                {
                    <div class="damage-resistances">
                        <h3>Damage Resistances</h3>
                        <p>@Model.DamageResistances</p>
                    </div>
                }

                @if (!string.IsNullOrEmpty(Model.DamageVulnerabilities))
                {
                    <div class="damage-vulnerabilities">
                        <h3>Damage Vulnerabilities</h3>
                        <p>@Model.DamageVulnerabilities</p>
                    </div>
                }
            </div>
        </div>
  

DungeonsAndDragonsMonsterFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dungeons And Dragons Monster Finder</title>
    <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dungeons And Dragons Monster Finder.styles.css" asp-append-version="true" />
</head>
<body>
    <style>
        body {
            background-color: black;
        }
    </style>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex justify-content-center align-items-center">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dungeons And Dragons Monster Finder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item" style="margin-top: 15px;">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item" style="margin-top: 15px;">
                            <a class="nav-link text-light" asp-area="" asp-controller="Monsters" asp-action="Index">Monster Index</a>
                        </li>
                        <li class="nav-item">
                            <div class="d-flex justify-content-center align-items-center" style="margin-left: 20px;">
                                @using (Html.BeginForm("Search", "Monsters", FormMethod.Get))
                                {
                                    <p style="color: ivory; margin-top: 15px; ">
                                        Find by Name: @Html.TextBox("searchStringName")
                                        <input type="submit" value="Search" class="btn btn-outline-light">
                                    </p>
                                }
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>